name: Render CI

on:
    push:
        branches:
            - typescript # Change this to the branch you want to trigger the CI on

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16

            - name: Install dependencies
              run: npm ci

            - name: Lint code
              run: npm run lint

            - name: Run tests
              run: npm test
